version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mean-course-mongodb
    restart: unless-stopped
    ports:
      - '27018:27018'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mean-course
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - mean-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  mean-network:
    driver: bridge
